#!/usr/bin/env python3
"""riddl -51 gave folds `append <v> to field F`, `remove <v> from field F` and
`remove from field F where <key> == <v>`. Rewrite the collection folds the
corpus wrote as `set field F to prompt("… with x appended")` / `("… without
x")` into them, plus reactive-bbq's four `do "append/remove …"` folds. Each
site is a row below: (file, old text, new text). Validates each model after."""
import re,subprocess,sys
from pathlib import Path
ROOT=Path("/Users/reid/Code/ossuminc/riddl-models"); R="/Users/reid/Code/ossuminc/bin/riddlc"
S=lambda f,b,fld,v: (f, f'set field {fld} to prompt("', None)  # placeholder, unused
rows=[
 # (file, old, new)
 ("commerce/e-commerce/order-management/Shipment.riddl",
  'set field Shipment.Active.trackingHistory to prompt("the tracking history with a ShipmentEvent of status, location, description and updatedAt appended")',
  'append prompt("a ShipmentEvent of status, location, description and updatedAt") to field Shipment.Active.trackingHistory'),
 ("commerce/e-commerce/shopping-cart/Cart.riddl",
  'set field Cart.ActiveState.items to prompt("the items with the source cart\'s items merged in")',
  'foreach merged in prompt("the source cart\'s items") {\n        append merged to field Cart.ActiveState.items\n      }'),
 ("commerce/e-commerce/shopping-cart/Cart.riddl",
  'set field Cart.ActiveState.items to prompt("the items with item appended")',
  'append itemAdded.item to field Cart.ActiveState.items'),
 ("commerce/e-commerce/shopping-cart/Cart.riddl",
  'set field Cart.ActiveState.items to prompt("the items without productId")',
  'remove from field Cart.ActiveState.items where productId == itemRemoved.productId'),
 ("commerce/e-commerce/shopping-cart/Cart.riddl",
  'set field Cart.ActiveState.discounts to prompt("the discounts with discount appended")',
  'append promoCodeApplied.discount to field Cart.ActiveState.discounts'),
 ("commerce/e-commerce/shopping-cart/Cart.riddl",
  'set field Cart.ActiveState.discounts to prompt("the discounts without the one for code")',
  'remove from field Cart.ActiveState.discounts where code == promoCodeRemoved.code'),
 ("commerce/e-commerce/product-catalog/PriceList.riddl",
  'set field PriceList.ActivePriceListState.prices to prompt("the prices with an entry for productId at price, replacing any earlier one")',
  'remove from field PriceList.ActivePriceListState.prices where productId == productPriceSet.productId\n      append prompt("a ProductPriceEntry for productId at price") to field PriceList.ActivePriceListState.prices'),
 ("commerce/e-commerce/product-catalog/Product.riddl",
  'set field Product.Active.categories to prompt("the categories with categoryId added")',
  'append categoryAssigned.categoryId to field Product.Active.categories'),
 ("commerce/e-commerce/product-catalog/Product.riddl",
  'set field Product.Active.variants to prompt("the variants with variant appended")',
  'append variantAdded.variant to field Product.Active.variants'),
 ("hospitality/food-service/reactive-bbq/corporate/MenuRelease.riddl",
  'set field MenuRelease.ActiveRelease.releaseItems to prompt("the release items with releaseMenuItemId added or removed according to releaseAction")',
  'when prompt("releaseAction says remove") then\n        remove itemAddedToRelease.releaseMenuItemId from field MenuRelease.ActiveRelease.releaseItems\n      else\n        append itemAddedToRelease.releaseMenuItemId to field MenuRelease.ActiveRelease.releaseItems\n      end'),
 ("technology/devops/incident-management/Incident.riddl",
  'set field Incident.ActiveState.info.affectedServices to prompt("the affected services with additionalServices appended")',
  'foreach service in incidentEscalated.additionalServices {\n        append service to field Incident.ActiveState.info.affectedServices\n      }'),
 ("technology/devops/incident-management/Incident.riddl",
  'set field Incident.ActiveState.timeline to prompt("the timeline with entry appended")',
  'append timelineEntryAdded.entry to field Incident.ActiveState.timeline'),
 ("healthcare/life-sciences/clinical-trials/ClinicalStudy.riddl",
  'set field ClinicalStudy.ActiveState.sites to prompt("the sites with siteInfo appended")',
  'append siteActivated.siteInfo to field ClinicalStudy.ActiveState.sites'),
 ("healthcare/life-sciences/clinical-trials/ClinicalStudy.riddl",
  'set field ClinicalStudy.ActiveState.enrollments to prompt("the enrollments with enrollment appended")',
  'append subjectEnrolled.enrollment to field ClinicalStudy.ActiveState.enrollments'),
 ("healthcare/life-sciences/clinical-trials/ClinicalStudy.riddl",
  'set field ClinicalStudy.ActiveState.visits to prompt("the visits with visit appended")',
  'append visitRecorded.visit to field ClinicalStudy.ActiveState.visits'),
 ("healthcare/life-sciences/clinical-trials/ClinicalStudy.riddl",
  'set field ClinicalStudy.ActiveState.submissions to prompt("the submissions with submission appended")',
  'append dataSubmitted.submission to field ClinicalStudy.ActiveState.submissions'),
 ("healthcare/hospitals/radiology-workflow/ImagingExam.riddl",
  'set field ImagingExam.FinalizedState.addendums to prompt("the addendums with a report carrying addendumText and addendumReason appended")',
  'append prompt("a RadiologyReport carrying addendumText and addendumReason, signed by radiologistId at addedAt") to field ImagingExam.FinalizedState.addendums'),
 ("entertainment/live-events/ticket-sales/Ticket.riddl",
  'set field Ticket.SoldState.transferHistory to prompt("the transfer history with a record of fromBuyerId, toBuyerId and transferredAt appended")',
  'append prompt("a TransferRecord of fromBuyerId, toBuyerId and transferredAt") to field Ticket.SoldState.transferHistory'),
 ("manufacturing/maintenance/equipment-maintenance/MaintenanceOrder.riddl",
  'set field MaintenanceOrder.InProgressState.partsUsed to prompt("the parts used with a SparePartUsage of sparePartId, partNumber, quantity and totalCost appended")',
  'append prompt("a SparePartUsage of sparePartId, partNumber, quantity and totalCost") to field MaintenanceOrder.InProgressState.partsUsed'),
 ("professional-services/legal/case-management/LegalCase.riddl",
  'set field LegalCase.ActiveState.teamMembers to prompt("the team members with member appended")',
  'append teamMemberAssigned.member to field LegalCase.ActiveState.teamMembers'),
 ("professional-services/legal/case-management/LegalCase.riddl",
  'set field LegalCase.ActiveState.teamMembers to prompt("the team members without the one whose id is memberId")',
  'remove from field LegalCase.ActiveState.teamMembers where memberId == teamMemberRemoved.memberId'),
 ("professional-services/legal/case-management/LegalCase.riddl",
  'set field LegalCase.ActiveState.timeEntries to prompt("the time entries with timeEntry appended")',
  'append timeEntryRecorded.timeEntry to field LegalCase.ActiveState.timeEntries'),
 ("professional-services/legal/case-management/LegalCase.riddl",
  'set field LegalCase.ActiveState.expenses to prompt("the expenses with expense appended")',
  'append expenseRecorded.expense to field LegalCase.ActiveState.expenses'),
 ("professional-services/legal/case-management/LegalCase.riddl",
  'set field LegalCase.ActiveState.documents to prompt("the documents with document appended")',
  'append documentAdded.document to field LegalCase.ActiveState.documents'),
 ("professional-services/legal/case-management/LegalCase.riddl",
  'set field LegalCase.ActiveState.courtDates to prompt("the court dates with courtDate appended")',
  'append courtDateScheduled.courtDate to field LegalCase.ActiveState.courtDates'),
 ("professional-services/legal/case-management/LegalCase.riddl",
  'set field LegalCase.ActiveState.courtDates to prompt("the court dates without the one whose id is dateId")',
  'remove from field LegalCase.ActiveState.courtDates where dateId == courtDateCancelled.dateId'),
 ("professional-services/legal/case-management/LegalCase.riddl",
  'set field LegalCase.ActiveState.notes to prompt("the notes with note appended")',
  'append noteAdded.note to field LegalCase.ActiveState.notes'),
 ("marketing/campaigns/campaign-management/Campaign.riddl",
  'set field Campaign.DraftState.channelAllocations to prompt("the channel allocations with allocation added, replacing any for the same channel")',
  'remove from field Campaign.DraftState.channelAllocations where channelId == channelBudgetAllocated.allocation.channelId\n      append channelBudgetAllocated.allocation to field Campaign.DraftState.channelAllocations'),
 ("marketing/campaigns/campaign-management/Campaign.riddl",
  'set field Campaign.DraftState.targetAudiences to prompt("the target audiences with audience appended")',
  'append targetAudienceAdded.audience to field Campaign.DraftState.targetAudiences'),
 ("marketing/campaigns/campaign-management/Campaign.riddl",
  'set field Campaign.DraftState.targetAudiences to prompt("the target audiences without the one whose id is audienceId")',
  'remove from field Campaign.DraftState.targetAudiences where audienceId == targetAudienceRemoved.audienceId'),
 ("marketing/campaigns/campaign-management/Campaign.riddl",
  'set field Campaign.ActiveState.channelMetrics to prompt("the channel metrics with channelPerformance replacing any for the same channel")',
  'remove from field Campaign.ActiveState.channelMetrics where channelId == performanceMetricsRecorded.channelPerformance.channelId\n      append performanceMetricsRecorded.channelPerformance to field Campaign.ActiveState.channelMetrics'),
 ("finance/payments/payment-processing/Payment.riddl",
  'set field Payment.CapturedState.disputes to prompt("the disputes with dispute appended")',
  'append disputeRecorded.dispute to field Payment.CapturedState.disputes'),
 ("finance/payments/payment-processing/Payment.riddl",
  'set field Payment.CapturedState.refunds to prompt("the refunds with refund appended")',
  'append paymentRefunded.refund to field Payment.CapturedState.refunds'),
 ("finance/payments/digital-wallet/Wallet.riddl",
  'set field Wallet.ActiveState.transactions to prompt("the transactions with the top-up appended")',
  'append prompt("a WalletTransaction for the top-up") to field Wallet.ActiveState.transactions'),
 ("finance/payments/digital-wallet/Wallet.riddl",
  'set field Wallet.ActiveState.transactions to prompt("the transactions with the receipt of amount from senderWalletId appended")',
  'append prompt("a WalletTransaction for the receipt of amount from senderWalletId") to field Wallet.ActiveState.transactions'),
 ("finance/payments/digital-wallet/Wallet.riddl",
  'set field Wallet.ActiveState.transactions to prompt("the transactions with the transfer appended")',
  'append prompt("a WalletTransaction for the transfer") to field Wallet.ActiveState.transactions'),
 ("finance/payments/digital-wallet/Wallet.riddl",
  'set field Wallet.ActiveState.transactions to prompt("the transactions with the withdrawal appended")',
  'append prompt("a WalletTransaction for the withdrawal") to field Wallet.ActiveState.transactions'),
 ("finance/payments/digital-wallet/Wallet.riddl",
  'set field Wallet.ActiveState.transactions to prompt("the transactions with the payment appended")',
  'append prompt("a WalletTransaction for the payment") to field Wallet.ActiveState.transactions'),
 ("finance/payments/digital-wallet/Wallet.riddl",
  'set field Wallet.ActiveState.paymentMethods to prompt("the payment methods with method appended")',
  'append paymentMethodAdded.method to field Wallet.ActiveState.paymentMethods'),
 ("finance/payments/digital-wallet/Wallet.riddl",
  'set field Wallet.ActiveState.paymentMethods to prompt("the payment methods without methodId")',
  'remove from field Wallet.ActiveState.paymentMethods where methodId == paymentMethodRemoved.methodId'),
 ("insurance/property-casualty/policy-administration/Policy.riddl",
  'set field Policy.ActiveState.endorsements to prompt("the endorsements with endorsement appended")',
  'append endorsementAdded.endorsement to field Policy.ActiveState.endorsements'),
 ("insurance/property-casualty/policy-administration/Policy.riddl",
  'set field Policy.ActiveState.renewalHistory to prompt("the renewal history with renewalOffer appended")',
  'append renewalOfferGenerated.renewalOffer to field Policy.ActiveState.renewalHistory'),
 ("insurance/reinsurance/treaty-management/Treaty.riddl",
  'set field Treaty.ExecutedState.cessions to prompt("the cessions with cession appended")',
  'append cessionRecorded.cession to field Treaty.ExecutedState.cessions'),
 ("insurance/life-annuity/policy-lifecycle/LifePolicy.riddl",
  'set field LifePolicy.ActiveState.beneficiaries to prompt("the beneficiaries with beneficiary appended")',
  'append beneficiaryAdded.beneficiary to field LifePolicy.ActiveState.beneficiaries'),
 ("insurance/life-annuity/policy-lifecycle/LifePolicy.riddl",
  'set field LifePolicy.ActiveState.beneficiaries to prompt("the beneficiaries without beneficiaryId")',
  'remove from field LifePolicy.ActiveState.beneficiaries where beneficiaryId == beneficiaryRemoved.beneficiaryId'),
 ("insurance/life-annuity/policy-lifecycle/LifePolicy.riddl",
  'set field LifePolicy.ActiveState.premiumHistory to prompt("the premium history with payment appended")',
  'append premiumProcessed.payment to field LifePolicy.ActiveState.premiumHistory'),
 ("insurance/life-annuity/policy-lifecycle/LifePolicy.riddl",
  'set field LifePolicy.ActiveState.riders to prompt("the riders with rider appended")',
  'append riderAdded.rider to field LifePolicy.ActiveState.riders'),
 ("insurance/life-annuity/policy-lifecycle/LifePolicy.riddl",
  'set field LifePolicy.ActiveState.riders to prompt("the riders without riderId")',
  'remove from field LifePolicy.ActiveState.riders where riderId == riderRemoved.riderId'),
 # reactive-bbq's four do-folds and LoyaltyAccount's two
 ("hospitality/food-service/reactive-bbq/restaurant/TableOrder.riddl",
  'on event ItemAdded is {\n        do "append ItemAdded.addedItem to\n          TableOrderData.orderItems"\n      }',
  'on itemAdded: event ItemAdded is {\n        append itemAdded.addedItem to field TableOrder.Draft.orderItems\n      }'),
 ("hospitality/food-service/reactive-bbq/restaurant/TableOrder.riddl",
  'on event ItemRemoved is {\n        do "remove OrderLine from TableOrderData.orderItems\n          where orderLineItem.itemCode = ItemRemoved\n          .removedMenuItemId"\n      }',
  'on itemRemoved: event ItemRemoved is {\n        remove from field TableOrder.Draft.orderItems where itemCode == itemRemoved.removedMenuItemId\n      }'),
 ("hospitality/food-service/reactive-bbq/restaurant/OnlineOrder.riddl",
  'on event ItemAddedToCart is {\n        do "append ItemAddedToCart.cartItem to\n          OnlineOrderData.orderCartItems"\n      }',
  'on itemAddedToCart: event ItemAddedToCart is {\n        append itemAddedToCart.cartItem to field OnlineOrder.Browsing.orderCartItems\n      }'),
 ("hospitality/food-service/reactive-bbq/restaurant/OnlineOrder.riddl",
  'on event ItemRemovedFromCart is {\n        do "remove CartItem from OnlineOrderData\n          .orderCartItems where cartMenuItemId =\n          ItemRemovedFromCart.removedCartItemId"\n      }',
  'on itemRemovedFromCart: event ItemRemovedFromCart is {\n        remove from field OnlineOrder.Browsing.orderCartItems where cartMenuItemId == itemRemovedFromCart.removedCartItemId\n      }'),
]
def entry(d):
    for c in d.glob("*.conf"):
        m=re.search(r'input-file\s*=\s*"([^"]+)"',c.read_text())
        if m: return m.group(1)
touched=set()
for f,old,new in rows:
    fp=ROOT/f; t=fp.read_text()
    n=t.count(old)
    if n!=1: print(f"{f}: {n} matches for {old[:60]!r}"); continue
    fp.write_text(t.replace(old,new)); touched.add(fp.parent)
for d in sorted(touched):
    # model dir = the nearest ancestor with a .conf
    m=d
    while not list(m.glob("*.conf")): m=m.parent
    e=entry(m); p=subprocess.run([R,"--no-ansi-messages","--provide-tips","validate",e],cwd=m,capture_output=True,text=True); out=p.stdout+p.stderr
    errs=[l for l in out.splitlines() if l.startswith("[error]")]
    kinds=sorted(set(re.findall(r"^\[(\w+)\] \[([\w-]+)\]",out,re.M)))
    print(f"{m.relative_to(ROOT)}: {len(errs)} errors; {kinds}")
    for l in errs[:4]: print("   ",l)
